### ISSUE TITLE
[Feature]: Implementation of Hamburger menu.

### ISSUE THREAD

**Issue by Abhii5496** [Vin-Jex/dent-clack#101]
![image](https://github.com/user-attachments/assets/9100ef95-5a17-4b28-b7fe-8a506bbe14f5)

Implement hamburger menu on mobile devices for smooth user experience .

i would like to work on it , can you assign me this under hacktoberfest !!

**Comment by Vin-Jex** [comment]
Alright, this is a valid issue. I will assign it to you.
