### ISSUE TITLE
[Bug]: Day and Night mode are functioning opposite to it's icons

### ISSUE THREAD

**Issue by malavshah9** [Vin-Jex/dent-clack#105]
**Describe the bug**
As we can see in the screenshot below, we opened the deployed version of the web app and found that the day and night version icons are opposite to its functioning.

**To Reproduce**
1. Go to https://dentclack.vercel.app/#services
2. Scroll to top
3. Observer day/night icons 

**Expected behavior**
When the toggle is on the moon icon, it should be night mode and day mode otherwise.

**Screenshots**
<img width="1438" alt="Screenshot 2024-10-24 at 11 43 35 PM" src="https://github.com/user-attachments/assets/d39a5921-ebea-407d-82dd-2d8627108cee">

**Additional context**
- If you find this issue, please assign it to me. I will work on this.

**Comment by thanhloc03** [comment]
I can solve this issue, can you assign it to me?
