### ISSUE TITLE
[Feature]: create Footer 

### ISSUE THREAD

**Issue by Anthony-Chima** [Vin-Jex/dent-clack#108]
Would like to complete the landing page with the footer.

**Comment by thanhloc03** [comment]
I am interesting with this project, can you say detail description works I can do?

**Comment by Vin-Jex** [comment]
> Would like to complete the landing page with the footer.

Drop a detailed description and an image of what you would be working on.

**Comment by Vin-Jex** [comment]
> I am interesting in this project, can you say detail description works I can do?, If possible can you assign to me

Have you reviewed all opened issues? There’s no one you can work on? 

I will open more issues in 30 minutes.

**Comment by Anthony-Chima** [comment]
The Landing Page is yet to have a footer
I wish to work on the footer of the landing page
<img width="512" alt="footer img" src="https://github.com/user-attachments/assets/9e9a281e-a5a1-4c43-b2d5-4dbadf31f188">
