### ISSUE TITLE
[Bug]: Hydration Error

### ISSUE THREAD

**Issue by Vin-Jex** [Vin-Jex/dent-clack#111]
**Describe the bug**
Hydration Error and error related to a layout file.

**To Reproduce**
1. Clone the application.
2. Install the required dependencies
3. Start the development server.
4. You will find the error.

**Expected behavior**
Clear of all error, especially hydration kind of errors and warnings.

**Desktop (please complete the following information):**
 - OS: All OS
 - Browser: All browsers

**Smartphone (please complete the following information):**
 - Device: All devices
 - OS: All OS
 - Browser: All browsers

**Comment by Oyinda08** [comment]
hi @Vin-Jex can you please assign me to this issue.

**Comment by Oyinda08** [comment]
@Oyinda08 Alright, I will do that.
