### ISSUE TITLE
Upgrade Application from JavaScript to NextJs

### ISSUE THREAD

**Issue by Vin-Jex** [Vin-Jex/dent-clack#69]
# Upgrade Application from JavaScript to NextJs

## Technologies Required for Upgrade
- TypeScript
- NextJS - App Router
- TailwindCss
- Material UI
- Material Icon
- SwiperJS

**Comment by Jackdrakes** [comment]
I  like to contribute here. 

I was so confused to see the branches. 
Can you structure  the things or mention about your setup in a seperate readme.md file. 
@Vin-Jex

**Comment by Jackdrakes** [comment]
which is the production branch

**Comment by Jackdrakes** [comment]
@Vin-Jex  which is the prod branch?

**Comment by Vin-Jex** [comment]
@Jackdrakes You can now go through the documentation again, it was just updated. Happy contribution!
