### ISSUE TITLE
Update the current Top Navbar.

### ISSUE THREAD

**Issue by Vin-Jex** [Vin-Jex/dent-clack#77]
- Below Contains the figma design of how the top navigation should look like.
![Screenshot 2024-10-01 at 5 08 29 AM](https://github.com/user-attachments/assets/f1027422-cc33-4a3f-923f-e923488faf68)

**Comment by Muskan2404** [comment]
I'd like to do it. Can you assign me this?

**Comment by Anthony-Chima** [comment]
I would like to get assigned to this.

**Comment by Vin-Jex** [comment]
> I would like to get assigned to this.

You can proceed to contributing.

**Comment by AnanteshG** [comment]
Can I get assigned to this?

**Comment by Vin-Jex** [comment]
> Can I get assigned to this?

This task has already been assigned to someone, but I'll be creating more issues shortly. Please review them and request assignment if it's something you can handle.
