### ISSUE TITLE
Update the Current Hero Section.

### ISSUE THREAD

**Issue by Vin-Jex** [Vin-Jex/dent-clack#78]
- Below contains how the hero section would look like.
- Ensure your PR is 85% close to the image below before creating a pull request
![Screenshot 2024-10-01 at 5 08 29 AM 2](https://github.com/user-attachments/assets/4201f150-786a-43a6-97df-fa79c50b7c55)

**Comment by bulutyerli** [comment]
I would like to work on this, can you assign this to me?

**Comment by Vin-Jex** [comment]
> I would like to work on this, can you assign this to me?

Of course, I will assign it to you.
