### ISSUE TITLE
[Feature]: Create Layout for Authentication Pages

### ISSUE THREAD

**Issue by Vin-Jex** [Vin-Jex/dent-clack#84]
**Is your feature request related to a problem? Please describe.**
Currently, in version 2 of the project, there is no dedicated authentication page. As a result, the flow begins with layout pages instead of a proper authentication flow or login interface.

**Describe the solution you'd like**
I would like to avoid duplicating layout elements across multiple pages. The goal is to implement a reusable layout that can be consistently applied to all pages, including the authentication pages.

**Below is the proposed UI for the Authentication Page:**
![Screenshot 2024-10-01 at 5 09 50 AM](https://github.com/user-attachments/assets/a8957988-c7d0-41cb-bad6-04e3f7ba0376)

**Comment by SR2090** [comment]
I understand the requirement you need a sign up form with buttons. By reusable you mean one text component that can be used for the different fields and one button component that can be reused for layout. A resource file where we can provide the name and the type of the field based on which validation will be provided. And finally the actual layout of the page that will use the components.
I can work on this if you assign it to me. If its anything else then do let me know exactly what do you need as it seems interesting.

**Comment by Vin-Jex** [comment]
Seems like everyone is struggling to look into this issue so I will resolve it in a moment.

**Comment by Oyinda08** [comment]
Hello @Vin-Jex  can you assign me to this issue?
