### ISSUE TITLE
[Feature]: Authentication Page ( Sign In ) 

### ISSUE THREAD

**Issue by Vin-Jex** [Vin-Jex/dent-clack#86]
### **Is your feature request related to a problem? Please describe.**

At the moment, the project does not have a dedicated signin page.

### **Describe the solution you'd like**

- Design and implement a **responsive signup page**, ensuring it integrates seamlessly with the existing layout used for the left content.
- Ensure the page adapts to both light and dark themes, maintaining a visually appealing design when toggling between themes.
- Include **loading states** for the buttons and **validation states** for the input fields to enhance user experience and feedback.

### **Describe alternatives you've considered**

I have considered using existing components from other authentication pages, but a dedicated, customized signup page will provide better control and a tailored user experience.

### **Additional context**

![Screenshot 2024-10-01 at 5 09 55 AM](https://github.com/user-attachments/assets/c82e48b4-93c8-4c4e-948e-18ab2f577b43)

**Comment by Neel-07** [comment]
can this issue be assigned to me @Vin-Jex

**Comment by Vin-Jex** [comment]
> can this issue be assigned to me @Vin-Jex

Of course, I can assign it to you but first you need to make a decision on the issue you want to be assigned to. You can’t be assigned more than one issue at a time.

**Comment by Neel-07** [comment]
i can get started with this issue  @Vin-Jex, btw can we use clerk components for sigin?

**Comment by Vin-Jex** [comment]
> i can get started with this issue @Vin-Jex, btw can we use clerk components for sigin?

Yes, you can use the components directory for creating signin component but make sure to use either camalCase or PascalCase for file naming.

**Comment by Neel-07** [comment]
@Vin-Jex  can i get the exact image use in the context or else can i use any other image of that sort?

**Comment by Vin-Jex** [comment]
@Neel-07 I've been getting report about the error being thrown when the user tries run this project after cloning there folk and this started happening after I merge your PR so I will revert the PR now. Thank you!

**Comment by Neel-07** [comment]
@Vin-Jex  can you specify the error type, maybe it is due  to not adding the  clerk secret and publishable keys in the .env.local file

**Comment by Vin-Jex** [comment]
@Oyinda08 This is the issue you just raised. Come implement the feature here.

**Comment by Oyinda08** [comment]
@Vin-Jex can you please assign it to me.

**Comment by Vin-Jex** [comment]
@Oyinda08 I will do that now.

**Comment by Oyinda08** [comment]
@Vin-Jex Thank you!

**Comment by Vin-Jex** [comment]
@Oyinda08 You are yet to give an update on this issue.

**Comment by Oyinda08** [comment]
hello @Vin-Jex please assign me to this issue..

**Comment by Vin-Jex** [comment]
@Oyinda08 I already assigned it to you.
