### ISSUE TITLE
[Feature]: Create a Services We Offer

### ISSUE THREAD

**Issue by Vin-Jex** [Vin-Jex/dent-clack#89]
### **Is your feature request related to a problem? Please describe.**

The landing page currently lacks a dedicated section to showcase the dental services offered and introduce the specialists, making it difficult for users to understand what services are available and who the specialists are.

### **Describe the solution you'd like**

- Create a **Services We Offer** section that clearly outlines the dental services provided (e.g., teeth cleaning, orthodontics, dental surgery) with brief descriptions for each service.
- Design a **Our Specialists** section that highlights the dental professionals, including their names, roles, and a short bio or expertise area. Add professional images of the specialists to make the section more personal and trustworthy.
- Ensure both sections are visually appealing, responsive, and align with the overall theme of the landing page. Each section should use icons, images, or cards for easy readability and engagement.
- Smooth transitions between the sections should maintain the user flow, following after the **About** section.

### **Describe alternatives you've considered**

One alternative considered was consolidating these sections into a single block on the landing page, but separating them will improve readability and make the content more digestible.

### **Additional context**
![Screenshot 2024-10-01 at 5 09 01 AM](https://github.com/user-attachments/assets/a3ca000b-03d6-436a-b2bf-e03e196394d3)

**Comment by Anthony-Chima** [comment]
I would like to get assigned this issue.

**Comment by Vin-Jex** [comment]
> I would like to get assigned this issue.

You can go ahead to contribute!
