### ISSUE TITLE
[Bug]: Theme Toggle Button Enhancement

### ISSUE THREAD

**Issue by Vin-Jex** [Vin-Jex/dent-clack#91]
**Describe the bug**
I believe the ball inside of the container should not overflow or overlay the parent container.

**To Reproduce**
1. Visit dent clack domain or url
2. In the top navigation, you would find a theme toggle button.
4. You will notice that the toggle UI is not good enough

**Expected behavior**
- The toggle container should be bigger than the ball inside it
- There should be a transitioning effect when toggling theme.

**Screenshots**
<img width="1680" alt="Screenshot 2024-10-03 at 7 37 19 AM" src="https://github.com/user-attachments/assets/6c28627f-570e-4ba2-ae51-0a093a10699e">

**Desktop (please complete the following information):**
 - On any OS
 - Browser: Any browser

**Smartphone (please complete the following information):**
 - Device: iPhone 
 - On any browser.

**Comment by gaurimadan** [comment]
@Vin-Jex i would like to take this issue

**Comment by Anthony-Chima** [comment]
I believe I have fixed this issue when assigned to updating the top Nabar I just need to make a pull request for code review, so can I get also get assigned this issue.
