### ISSUE TITLE
[Feature]:  Login page

### ISSUE THREAD

**Issue by Oyinda08** [Vin-Jex/dent-clack#98]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Adding a login page for users.

**Describe alternatives you've considered**
No other alternative.

**Additional context**
<img width="806" alt="Screenshot 2024-10-12 at 14 42 29" src="https://github.com/user-attachments/assets/82554f11-e5f9-467b-99c6-db1be555c92c">

**Comment by Oyinda08** [comment]
Hi @Vin-Jex can you please allow me to work on the login page.

**Comment by Vin-Jex** [comment]
> Hi @Vin-Jex can you please allow me to work on the login page.

Thank you for your interest in contributing. However, this issue has been raised before and it is still open for grab please. Asked me to assign it to you if you're interested. Thank you.

**Comment by Vin-Jex** [comment]
> Hi @Vin-Jex can you please allow me to work on the login page.

I will go ahead and close it now.

**Comment by Oyinda08** [comment]
Hi @Vin-Jex can you please assign me ?
